### ISSUE TITLE
SOLID Icons Not Appearing in iOS

### ISSUE THREAD

**Issue by mzhukovs** [coolc0ders/FontAwesome5XamarinForms#1]
Question - are you able to actually get the SOLID icons to appear in iOS? i.e. these 2 from your example:  &#xf2a3;     &#xf0f9;

When I run (in iOS simulator), I can't get them to render (only question marks appear). No issues with Regular or even Brand icons, but Solid won't come up. I tried both with .otf and .ttf - no luck. Please let me know, thanks.

**Comment by mzhukovs** [comment]
ok figured it out... FYI you need to add **FontAttributes = Bold** in the XAML to make them appear in iOS, and for some reason it only works with the otf (can't make the icons show with the .ttf solid file no matter what).

**Comment by DamienDoumer** [comment]
Hi, I made notes about such issues at the end of the tutorial.
Reading it till the end will avoid you running into such trouble and save you time.
And also, I mentioned that the extensions for the icons were otf instead of ttf.

**Comment by DamienDoumer** [comment]
ttf is the file extension not otf, so it wont work with otf.

**Comment by mzhukovs** [comment]
Damien, if you're referring to [this post](https://doumer.me/icons-with-font-awesome-5-xamarin-forms/), you are mistaken - nowhere in that article do you mention that FontAttributes on the label should be set to "Bold" to make solid icons appear in iOS, nor is it in your XAML. Your response was not only incorrect, but also came off as a bit rude. Also your 2 responses contradict each other: "I mentioned that the extensions for the icons were otf instead of ttf." followed by "ttf is the file extension not otf, so it wont work with otf".   As mentioned, the FontAttributes=Bold for iOS only worked with the .otf file for the solid icons. I used .ttf for everything else and on all other platforms. I was giving you this information so that you could update your incomplete article and example, but you can choose to continue to ignore it if you wish.

**Comment by DamienDoumer** [comment]
OK, I didn't mean to be rude if you find I was rude, sorry.
But in case there is any misunderstanding from my side, please post the peace of xaml code which made it work on your side. And if I misunderstood you and made an error, I'll update the post and the code so that no one faces that issue.
Thanks.

**Comment by DamienDoumer** [comment]
Also, please. Check again the post well.
at the end, I mentioned the issue about only solid fonts being avalable due to pricing made on some regular and light fonts: Look at this screenshot from the post:
![correction](https://user-images.githubusercontent.com/16731017/41277630-acf74ee0-6e1f-11e8-80b1-69190871b514.png)

**Comment by DamienDoumer** [comment]
And also, please post your xaml code here, in case I'm wrong, I will reopen this issue till I make changes on the post and the code. Some other people may be facing the problem you are facing.  
Thanks.

**Comment by mzhukovs** [comment]
Hi Damien - no worries, let's move on. The issue has nothing to do with the availability of the solid icons - it is that the ones that are available for free won't render in iOS unless you set the FontAttributes property on the Label to Bold. I didn't provide the code because that is literally the only change you need to make, but to be explicit, here is what's in the article now (just looking at the first solid icon used, but the same change would have to be made for all solid icons):

```
        <Label Text="&#xf00c;" 
           FontSize="50"
           TextColor="SkyBlue"
           VerticalOptions="Center" 
           HorizontalOptions="Center" >
            <Label.FontFamily>
                <OnPlatform x:TypeArguments="x:String"
                        Android="Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free Solid" 
                        iOS="Font Awesome 5 Free" 
                        WinPhone="Assets/Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free" />
            </Label.FontFamily>
        </Label>
```

And here is what it needs to be updated to (for the icon to appear properly on iOS):
```
        <Label Text="&#xf00c;" 
           FontSize="50"
```
:exclamation:
`           FontAttributes="Bold"`
:exclamation:
```
           TextColor="SkyBlue"
           VerticalOptions="Center" 
           HorizontalOptions="Center" >
            <Label.FontFamily>
                <OnPlatform x:TypeArguments="x:String"
                        Android="Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free Solid" 
                        iOS="Font Awesome 5 Free" 
                        WinPhone="Assets/Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free" />
            </Label.FontFamily>
        </Label>
```

**Comment by DamienDoumer** [comment]
Ok, thanks for your tip.
I'll then reopen this issue till I update the blog post, so that everyone is aware of it.

**Comment by mzhukovs** [comment]
No problem, thanks for the article. As an FYI, this is basically the Xamarin Forms XAML equivalent to handling the [font-weight issue described here](https://github.com/FortAwesome/Font-Awesome/issues/11946) for the solid icons here for the web, where they wouldn't appear unless in the css you explicitly set font-weight: 900;

**Comment by DamienDoumer** [comment]
Cool 👍

**Comment by DamienDoumer** [comment]
I updated the post with a tip to anyone who may face this issue. [HERE](https://doumer.me/icons-with-font-awesome-5-xamarin-forms/)
![fontawesome](https://user-images.githubusercontent.com/16731017/41345503-c72a67e8-6efb-11e8-8c38-1632e8a6e7bf.PNG)
So, I'll now close this issue.

**Comment by DamienDoumer** [comment]
I'll also send a push notification to all my subscribed readers about the update.
